/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package Frontend;

import Backend.LexicalAnalyzer;
import javax.swing.JOptionPane;

/**
 *
 * @author brigidoalvarado
 */
public class AnalyzerApp extends javax.swing.JFrame {

    private  LexicalAnalyzer lexicalAnalyzer = new LexicalAnalyzer();
    private Pixel[][] canvas;

    /**
     * Creates new form AnalyzerApp
     */
    public AnalyzerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorContainer = new javax.swing.JPanel();
        chargeFilejBttn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        imputjTxtAr = new javax.swing.JTextArea();
        rowNumberjTxtFld = new javax.swing.JTextField();
        columnNumberjTxtFld = new javax.swing.JTextField();
        rowNumberjLbl = new javax.swing.JLabel();
        columnNumberjLbl = new javax.swing.JLabel();
        printjBttn = new javax.swing.JButton();
        containerCanvasjPnl = new javax.swing.JPanel();
        jMnBr = new javax.swing.JMenuBar();
        ReportjMn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        editorContainer.setBackground(new java.awt.Color(102, 102, 102));
        editorContainer.setForeground(new java.awt.Color(102, 102, 102));
        editorContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chargeFilejBttn.setText("Cargar Archivo");
        editorContainer.add(chargeFilejBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 570, -1));

        imputjTxtAr.setColumns(20);
        imputjTxtAr.setRows(5);
        jScrollPane.setViewportView(imputjTxtAr);

        editorContainer.add(jScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 560, 368));
        editorContainer.add(rowNumberjTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 40, -1));
        editorContainer.add(columnNumberjTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 56, -1));

        rowNumberjLbl.setText("Filas");
        editorContainer.add(rowNumberjLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 40, -1));

        columnNumberjLbl.setText("Columnas");
        editorContainer.add(columnNumberjLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        printjBttn.setText("PINTAR");
        printjBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printjBttnActionPerformed(evt);
            }
        });
        editorContainer.add(printjBttn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 410, -1));

        ReportjMn.setText("Reportes");
        jMnBr.add(ReportjMn);

        setJMenuBar(jMnBr);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(editorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerCanvasjPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editorContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerCanvasjPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printjBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printjBttnActionPerformed
        // TODO add your handling code here:
        try {
            int row = Integer.parseInt(rowNumberjTxtFld.getText());
            int column = Integer.parseInt(columnNumberjTxtFld.getText());
            canvas = new Pixel [row][column];
            String input = imputjTxtAr.getText();
            System.out.println(input);
            lexicalAnalyzer = new LexicalAnalyzer();
            lexicalAnalyzer.analyze(input, canvas);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Numero invalido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_printjBttnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportjMn;
    private javax.swing.JButton chargeFilejBttn;
    private javax.swing.JLabel columnNumberjLbl;
    private javax.swing.JTextField columnNumberjTxtFld;
    private javax.swing.JPanel containerCanvasjPnl;
    private javax.swing.JPanel editorContainer;
    private javax.swing.JTextArea imputjTxtAr;
    private javax.swing.JMenuBar jMnBr;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JButton printjBttn;
    private javax.swing.JLabel rowNumberjLbl;
    private javax.swing.JTextField rowNumberjTxtFld;
    // End of variables declaration//GEN-END:variables

}
