/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/Application.java to edit this template
 */
package Frontend;

import Backend.analyzers.LexicalAnalyzer;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author brigidoalvarado
 */
public class AnalyzerApp extends javax.swing.JFrame {
    private  LexicalAnalyzer lexicalAnalyzer;
    private Pixel[][] canvas;

    /**
     * Creates new form AnalyzerApp
     */
    public AnalyzerApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editorContainer = new javax.swing.JPanel();
        chargeFilejBttn = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        inputjTxtAr = new javax.swing.JTextArea();
        positionjLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rowNumberjLbl = new javax.swing.JLabel();
        rowNumberjTxtFld = new javax.swing.JTextField();
        columnNumberjLbl = new javax.swing.JLabel();
        columnNumberjTxtFld = new javax.swing.JTextField();
        containerCanvasjPnl = new javax.swing.JPanel();
        jMnBr = new javax.swing.JMenuBar();
        ReportjMn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        editorContainer.setBackground(new java.awt.Color(204, 204, 255));
        editorContainer.setForeground(new java.awt.Color(204, 204, 255));

        chargeFilejBttn.setText("Importar Archivo Fuente");
        chargeFilejBttn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargeFilejBttnActionPerformed(evt);
            }
        });

        inputjTxtAr.setColumns(20);
        inputjTxtAr.setRows(5);
        inputjTxtAr.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                inputjTxtArCaretUpdate(evt);
            }
        });
        jScrollPane.setViewportView(inputjTxtAr);

        positionjLbl.setText("linea :1 columna: 1");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Tamaño del Lienzo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 0, 0)))); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        rowNumberjLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rowNumberjLbl.setText("Filas");
        jPanel1.add(rowNumberjLbl);

        rowNumberjTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowNumberjTxtFldActionPerformed(evt);
            }
        });
        jPanel1.add(rowNumberjTxtFld);

        columnNumberjLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        columnNumberjLbl.setText("Columnas");
        jPanel1.add(columnNumberjLbl);

        columnNumberjTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnNumberjTxtFldActionPerformed(evt);
            }
        });
        jPanel1.add(columnNumberjTxtFld);

        javax.swing.GroupLayout editorContainerLayout = new javax.swing.GroupLayout(editorContainer);
        editorContainer.setLayout(editorContainerLayout);
        editorContainerLayout.setHorizontalGroup(
            editorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorContainerLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(positionjLbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editorContainerLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(editorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane)
                    .addGroup(editorContainerLayout.createSequentialGroup()
                        .addComponent(chargeFilejBttn, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        editorContainerLayout.setVerticalGroup(
            editorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editorContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(editorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chargeFilejBttn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(positionjLbl)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        getContentPane().add(editorContainer);

        containerCanvasjPnl.setPreferredSize(new java.awt.Dimension(480, 480));

        javax.swing.GroupLayout containerCanvasjPnlLayout = new javax.swing.GroupLayout(containerCanvasjPnl);
        containerCanvasjPnl.setLayout(containerCanvasjPnlLayout);
        containerCanvasjPnlLayout.setHorizontalGroup(
            containerCanvasjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );
        containerCanvasjPnlLayout.setVerticalGroup(
            containerCanvasjPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 512, Short.MAX_VALUE)
        );

        getContentPane().add(containerCanvasjPnl);

        ReportjMn.setText("Reportes");
        jMnBr.add(ReportjMn);

        setJMenuBar(jMnBr);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rowNumberjTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowNumberjTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowNumberjTxtFldActionPerformed

    private void columnNumberjTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnNumberjTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnNumberjTxtFldActionPerformed

    private void inputjTxtArCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_inputjTxtArCaretUpdate
        // TODO add your handling code here:
         try {
            int row = Integer.parseInt(rowNumberjTxtFld.getText());
            int column = Integer.parseInt(columnNumberjTxtFld.getText());
            updateCaretPosition();
            String input = inputjTxtAr.getText();
            lexicalAnalyzer = new LexicalAnalyzer();
            createCanvas(row, column);
            lexicalAnalyzer.analyze(input, canvas);
            updateCanvas(row, column);
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El numero ingresado en la fila o columna es un valor invalido", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
       
    }//GEN-LAST:event_inputjTxtArCaretUpdate

    private void chargeFilejBttnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargeFilejBttnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargeFilejBttnActionPerformed

    private void createCanvas(int row, int column){
        canvas = new Pixel[row][column];
            for (int i = 0; i < canvas.length; i++) {
                for (int j = 0; j < canvas[i].length; j++) {
                    canvas[i][j] = new Pixel();
                }
            }
    }
    
    private void updateCaretPosition(){
        try {
            int caretPos = inputjTxtAr.getCaretPosition(); // Obtiene la posición del cursor
            int line = inputjTxtAr.getLineOfOffset(caretPos); // Calcula la línea actual (fila)
            int column = caretPos - inputjTxtAr.getLineStartOffset(line); // Calcula la columna actual
            positionjLbl.setText("Fila: " + (line + 1) + ", Columna: " + (column + 1));
        } catch (BadLocationException ex) {
            JOptionPane.showMessageDialog(this, "error al actualizar la linea y columna ", "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }

    
    private void updateCanvas(int rows, int columns){
        containerCanvasjPnl.removeAll();
        containerCanvasjPnl.setLayout(new GridLayout(rows, rows));
        for (Pixel[] canva : canvas) {
            for (Pixel pixel : canva) {
                containerCanvasjPnl.add(pixel);
            }
        }
        containerCanvasjPnl.repaint();
        containerCanvasjPnl.revalidate();
        this.pack();
        this.repaint();
        this.revalidate();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ReportjMn;
    private javax.swing.JButton chargeFilejBttn;
    private javax.swing.JLabel columnNumberjLbl;
    private javax.swing.JTextField columnNumberjTxtFld;
    private javax.swing.JPanel containerCanvasjPnl;
    private javax.swing.JPanel editorContainer;
    private javax.swing.JTextArea inputjTxtAr;
    private javax.swing.JMenuBar jMnBr;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JLabel positionjLbl;
    private javax.swing.JLabel rowNumberjLbl;
    private javax.swing.JTextField rowNumberjTxtFld;
    // End of variables declaration//GEN-END:variables

}
